default_environment: default

environments:
  default:
    connections:
      duckdb:
        - name: "duckdb-default"
          path: "md:cryptoflow"
          token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im91c3NvdS5kZXYAZ21haWwuY29tIiwibWRSZWdpb24iOiJhd3MtZXUtY2VudHJhbC0xIiwic2Vzc2lvbiI6Im91c3NvdS5kZXYuZ21haWwuY29tIiwicGF0IjoiaTRvQkNPSWVQRHpNUVJxdWVXcktmdFNpcXFTd1gzNHpyX3dxamlBNDBWcyIsInVzZXJJZCI6IjNjMDIxMmQ2LTA1NzctNDc4OC05YmEzLTYxZGVlZjg0OTQxMyIsImlzcyI6Im1kX3BhdCIsInJlYWRPbmx5IjpmYWxzZSwidG9rZW5UeXBlIjoicmVhZF93cml0ZSIsImlhdCI6MTc3NDAxNTA5MH0.3PT9baEZrETLZuBy9zgsEE1TSuYQloefYMqoMIuPemk"